services:
  public-ip-web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: public-ip-web
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REFRESH_SECONDS=10
    restart: unless-stopped

